### ISSUE TITLE
Clearing cursor before setting spiderton home doesn't cancel the action

### ISSUE THREAD

**Issue by jim-hart** [asvanberg/spidertron-control-center#1]
If the new-home-set process is cancelled (by clearing what's in the player's hand), the next selection in game that triggers `events.on_player_selected_area` will result in a home being set regardless of the tool used to make that selection.  As an example, if we are using something like [Max Rate Calculator ](https://mods.factorio.com/mod/MaxRateCalculator):

1. initiate set home action
2. cancel action by clearing cursor 
3. select something using max rate calculator
4. spidertron's home from step `1` is set to the selection made by the max rate tool

Additionally, because the cursor is cleared after setting the new home, tools that provide a selection ability, but must be crafted, are deleted.

I don't know if this is the best way to handle the check, but I added the following [here in control.lua](https://github.com/asvanberg/spidertron-control-center/blob/master/control.lua#L344) and it fixed the issue locally:

```lua
    -- snip
    local spidertron = global.players[event.player_index].setting_home_for
    if event.item ~= "scc-set-home-tool" then
      if spidertron then 
        global.players[event.player_index].setting_home_for = nil
      end
      return
    end
    -- snip
```

**Comment by asvanberg** [comment]
Thanks for the bugreport.

**Comment by jim-hart** [comment]
@asvanberg No problem, and thanks for the mod, it's a great addition!
