### ISSUE TITLE
Ability to change the order of spidertrons in the control center list

### ISSUE THREAD

**Issue by ajklotz** [asvanberg/spidertron-control-center#2]

**Comment by asvanberg** [comment]
Would a fixed sort order, by name for example, be a good step forward or is custom ordering required?

**Comment by ajklotz** [comment]
> Would a fixed sort order, by name for example, be a good step forward or is custom ordering required?

Yes, this would be a good start, because I can name my spidertrons in a fashion that puts them in the order by a fixed sort order.
